<a href="https://colab.research.google.com/github/szymonszwedzinskiii/DataTemplates/blob/main/DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [36]:
X,y = load_iris(return_X_y=True)
print(X)
def count_gini(y):
  counts = np.bincount(y)
  pA = counts[0]/len(y)
  pB = counts[1]/len(y)
  pC = counts[2]/len(y)
  gini = 1- (0.33 * 0.33 + 0.33 * 0.33 + 0.33 * 0.33)
  print(f"Gini = {gini}")
  return gini


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [37]:
def most_common_class(y):
    values, counts = np.unique(y, return_counts=True)
    return values[np.argmax(counts)]

In [38]:
def find_best_split(X, y):
    n_samples, n_features = X.shape
    best_gini = 1.0
    best_feature, best_threshold = None, None

    for feature_index in range(n_features):
        thresholds = np.unique(X[:, feature_index])
        for threshold in thresholds:
            left_mask = X[:, feature_index] < threshold
            right_mask = ~left_mask

            if sum(left_mask) == 0 or sum(right_mask) == 0:
                continue

            y_left, y_right = y[left_mask], y[right_mask]

            gini_left = count_gini(y_left)
            gini_right = count_gini(y_right)

            weighted_gini = (len(y_left) * gini_left + len(y_right) * gini_right) / n_samples

            if weighted_gini < best_gini:
                best_gini = weighted_gini
                best_feature = feature_index
                best_threshold = threshold

    return best_feature, best_threshold

In [39]:
def build_tree(X,y,depth,max_depth=5,min_samples_split=2):
  if np.unique(y).size ==1:
    return {'leaf':y[0]}
  if depth >= max_depth:
    return {"leaf":most_common_class(y)}

  if len(y) < min_samples_split:
        return {'leaf': most_common_class(y)}

  best_feature, best_threshold = find_best_split(X, y)


  left_idx = X[:, best_feature] < best_threshold
  right_idx = ~left_idx

  if np.sum(left_idx) == 0 or np.sum(right_idx) == 0:
      return {'leaf': most_common_class(y)}

  left_branch = build_tree(X[left_idx], y[left_idx], depth + 1)
  right_branch = build_tree(X[right_idx], y[right_idx], depth + 1)

  return {
      'feature': best_feature,
      'threshold': best_threshold,
      'left': left_branch,
      'right': right_branch
  }
tree = build_tree(X,y,0,5)
print(tree)

IndexError: index 1 is out of bounds for axis 0 with size 1